[workspace]
changelog_update = false
git_release_enable = false
release_always = false
semver_check = false
publish_no_verify = true

[[package]]
name = "retrom"
git_release_enable = true

[[package]]
name = "retrom-client"
changelog_update = true
changelog_path = "./CHANGELOG.md"

[[package]]
name = "retrom-server"
changelog_update = true
changelog_path = "./CHANGELOG.md"

[changelog]
body = """

## `{{ package }}` - [{{ version | trim_start_matches(pat="v") }}]{%- if release_link -%}({{ release_link }}){% endif %} - {{ timestamp | date(format="%Y-%m-%d") }}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
{%- if commit.scope -%}
- *({{commit.scope}})* {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}{%- if commit.links %} ({% for link in commit.links %}[{{link.text}}]({{link.href}}) {% endfor -%}){% endif %}
{% else -%}
- {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}
{% endif -%}
{% endfor -%}
{% endfor -%}
"""

commit_parsers = [
  { message = "^feat", group = "added" },
  { message = "^fix", group = "fixed" },
]
