[workspace]
git_release_enable = false
git_tag_enable = false
release_always = false
semver_check = false
publish_no_verify = true
changelog_update = false

[[package]]
name = "retrom-service"
changelog_path = "./CHANGELOG.md"
changelog_update = true
changelog_include = ['retrom-client']
git_release_enable = true
git_tag_enable = true
git_release_name = "retrom-v{{ version }}"
git_tag_name = "retrom-v{{ version }}"

[changelog]
commit_parsers = [
  { message = "^feat", group = "added" },
  { message = "^fix", group = "fixed" },
]
body = """

## `{{ package }}` - [{{ version | trim_start_matches(pat="v") }}]{%- if release_link -%}({{ release_link }}){% endif %} - {{ timestamp | date(format="%Y-%m-%d") }}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
{%- if commit.scope -%}
- *({{commit.scope}})* {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}{%- if commit.links %} ({% for link in commit.links %}[{{link.text}}]({{link.href}}) {% endfor -%}){% endif %}
{% else -%}
- {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}
{% endif -%}
{%- if commit.body -%}
  {{ commit.body | indent(width=2) }}
{%- endif %}
{% endfor -%}
{% endfor -%}
"""
