[package]
name = "service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
dotenvy = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
library_manager = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
diesel = { workspace = true }
diesel-async = { workspace = true }
bb8 = { workspace = true }
db = { workspace = true }
uuid = { workspace = true }
generated = { workspace = true }
bytes = { workspace = true }
reqwest = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true }
prost = { workspace = true }
futures = { workspace = true }
tonic-web = "0.11.0"
deunicode = "1.4.4"
