[package]
name = "service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.5", features = ["http2"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
library_manager = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
diesel = { workspace = true }
diesel-async = { workspace = true }
bb8 = { workspace = true }
db = { workspace = true }
uuid = { workspace = true }
