namespace: retrom-helm

retrom:
  replicas: 1
  image:
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
  volumes:
    libraries:
      - name: retrom-library1
        type: pvc
        accessMode: ReadWriteMany
        mountPath: /library1
        size: 1Mi
        storageClass: nfs
        readOnly: false
    config:
      type: pvc
      storageClass: nfs
      size: 1Mi
      readOnly: false
      server: <server_ip>
      path: <nfs_path>/config
  service:
    type: NodePort
  ports:
    backend:
      nodePort: 31110
    frontend:
      nodePort: 31111

postgres:
  enabled: true
  image:
    pullPolicy: Always
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
  password: please_changeme_and_maybe_try_to_use_a_kubernetes_secret_:)
  service:
    type: ClusterIP
  ports:
    db:
      port: 5432
  pvc:
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Gi