namespace: retrom-helm

retrom:
  replicas: 1
  image:
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
  volumes:
    libraries:
      - name: retrom-library1
        type: pvc
        accessMode: ReadWriteMany
        mountPath: /library1
        size: 1Mi
        storageClass: nfs
        readOnly: false
    config:
      type: pvc
      storageClass: nfs
      size: 1Mi
      readOnly: false
      server: <server_ip>
      path: <nfs_path>/config
  # -- Optional: Cluster network service type
  service:
    type: NodePort
  ports:
    backend:
      # -- Optional: Port on which the service is exposed (when type is NodePort)
      nodePort: 31110
    frontend:
      # -- Optional: Port on which the web ui is exposed (when type is NodePort)
      nodePort: 31111

postgres:
  # -- Optional: Disable if you run your own postgres server.
  enabled: true
  image:
    pullPolicy: Always
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
  # -- Required: password for the postgres user. The username and database name will be "postgres".
  password: please_changeme_and_maybe_try_to_use_a_kubernetes_secret_:)
  # -- Required: storage for the postgres database
  pvc:
    # -- Required: Specify a StorageClass where the database will be stored
    storageClass: longhorn
    accessMode: ReadWriteOnce
    # -- Optional: Maximum size of the database
    size: 1Gi