namespace: retrom-helm

retrom:
  replicas: 1
  image:
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
  volumes:
    libraries:
      - name: retrom-library1
        type: pvc
        claimName: retrom-library1-pvc
        accessMode: ReadWriteMany
        mountPath: /library1
        size: 1Mi
        storageClass: nfs
    config:
      type: pvc
      claimName: retrom-config
      storageClass: nfs
      size: 1Mi
  type: NodePort
  ports:
    backend:
      port: 5101
      nodePort:
    frontend:
      port: 3000
      nodePort:

postgres:
  enabled: true
  replicas: 1
  image:
    pullPolicy: Always
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
  password: please_changeme_and_maybe_try_to_use_a_kubernetes_secret_:)
  type: ClusterIP
  ports:
    db:
      port: 5432
  pvc:
    storageClass: longhorn
    accessMode: ReadWriteMany
    size: 1Gi