[package]
name = "generated"
version = "0.1.0"
edition = "2021"

[lib]
name = "generated"

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
diesel = { workspace = true }
derive_builder = { workspace = true }
db = { workspace = true }

[build-dependencies]
tonic-build = "0.11"
walkdir = "2.5.0"
