[package]
name = "db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
diesel = { workspace = true }
diesel-async = { workspace = true }
bb8 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
dotenvy = { workspace = true }
derive_builder = { workspace = true }
uuid = { workspace = true }
generated = { workspace = true }
bigdecimal = "0.4.3"
async-trait = { workspace = true }
