[package]
name = "retrom-db"
version = "0.0.2"
description = "Database layer for Retrom"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
diesel = { workspace = true }
diesel-async = { workspace = true }
bb8 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
dotenvy = { workspace = true }
derive_builder = { workspace = true }
async-trait = { workspace = true }
