[package]
name = "db"
publish = false
version = "0.0.0"
authors.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
diesel = { workspace = true }
diesel-async = { workspace = true }
bb8 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
dotenvy = { workspace = true }
derive_builder = { workspace = true }
async-trait = { workspace = true }

[package.metadata.workspaces]
independent = true
