[package]
name = "library_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db = { path = "../db" }
diesel = { workspace = true }
serde = { version = "1.0.197", features = ["derive"] }
tokio = "1.37.0"
tracing = "0.1.40"
futures = { workspace = true }
uuid = { workspace = true }
generated = { workspace = true }
sha1 = "0.10.6"
