[package]
name = "retrom-library-manager"
publish = false
version = "0.0.0"
authors.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db = { path = "../db" }
diesel = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
generated = { workspace = true }
sha1 = "0.10.6"

[package.metadata.workspaces]
independent = true
